### ISSUE TITLE
ClassCast Exception (String <-> Spannable)

### ISSUE THREAD

**Issue by heinrichsusogym** [SusoGym/SEST-Android#16]
#### in de.konstanz.schulen.suso.activities.fragment.SubstitutionplanFragment$SubstitutionDataViewHolder.access$500

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/heinrichsusogymnasium-konstanz/android/apps/de.konstanz.schulen.suso/issues/5a64d89d8cb3c2fa634d85a8?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/heinrichsusogymnasium-konstanz/android/apps/de.konstanz.schulen.suso/issues/5a64d89d8cb3c2fa634d85a8?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by Smephite** [comment]
Spannable spannable = (Spannable) teacherView.getText();
in SubstitutionplanFragment.java
--> SpannableString?
