### ISSUE TITLE
onPushToForeground crash

### ISSUE THREAD

**Issue by heinrichsusogym** [SusoGym/SEST-Android#7]
#### in de.konstanz.schulen.suso.activities.fragment.SubstitutionplanFragment.onPushToForeground

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/heinrichsusogymnasium-konstanz/android/apps/de.konstanz.schulen.suso/issues/5a09f01361b02d480d5be87c?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/heinrichsusogymnasium-konstanz/android/apps/de.konstanz.schulen.suso/issues/5a09f01361b02d480d5be87c?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by Smephite** [comment]
Fix: 
MainActivity --> onCreate():
         setActiveFragment(SubstitutionplanFragment.class);
        navigationView.setCheckedItem(currentFragment.getNavigationId());
        disableUnknownNavItems();
nach onStart() verschieben
